### ISSUE TITLE
Missing dependency ECM

### ISSUE THREAD

**Issue by Milaine** [michalsrb/kdev-rust#1]
"~/kdev-rust/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 0.0.9) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!"

I have no idea what dependency I am missing, can you help me out?

**Comment by michalsrb** [comment]
ECM is Extra CMake Modules:
https://api.kde.org/ecm/manual/ecm.7.html
https://cgit.kde.org/extra-cmake-modules.git

In OpenSUSE it is in package called "extra-cmake-modules". I imagine it will be named similarly in other distributions.

**Comment by Milaine** [comment]
thank you, I'd advise to write it out like the other packages since I couldn't find it as ECM (there's two different packages you'd find first).

Also, your list of dependencies is very inspecific and I had trouble searching most of the packages, if there was a list of the packages needed that would greatly improve ease of installation.

**Comment by michalsrb** [comment]
I will see if I can improve the dependency description.
However, note that this project is just an experiment in early stage and isn't very useful for any real work at this moment. So a user-friendly installation is not on top of my list.
